import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TopNav from '@/components/top-nav'
import Footer from '@/components/footer'
import { ThemeProvider } from '@/contexts/themeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-screen justify-between items-center`}>
        <ThemeProvider>
          <TopNav />
          {children}
          <Footer />
        </ThemeProvider>

      </body>
    </html>
  )
}
